/code
language: ruby
rvm:
  - "2.0.0"

install:
  - bundle install --path .bundle --binstubs

script:
  - bundle exec rake db:migrate test:prepare
  - bundle exec rspec spec

after_script:

  - https://preview.ninefold.com/api/v1/apps/123/redeploy?auth_token=CKFVStyQCsRbKDk4RwJoZQ

