development:
  adapter: postgresql
  database: bloccit_dev
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: bloccit_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bloccit_prod
  pool: 5
  timeout: 5000

